# Generated by Django 5.0 on 2024-01-11 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modelservice", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagemodel",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterField(
            model_name="imagemodel",
            name="image",
            field=models.ImageField(
                upload_to="uploads/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterModelTable(
            name="imagemodel",
            table="custom_image_table",
        ),
    ]
