# Generated by Django 5.0 on 2024-01-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modelservice", "0003_predictionresult"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="predictionresult",
            name="class_id",
        ),
        migrations.RemoveField(
            model_name="predictionresult",
            name="confidence",
        ),
        migrations.AddField(
            model_name="predictionresult",
            name="class_label",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
