# Generated by Django 5.0 on 2024-01-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_customuser_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medifree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_title", models.CharField(max_length=255)),
                ("f_items", models.JSONField()),
                ("f_texts", models.JSONField()),
            ],
        ),
    ]
